plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.1'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'org.ec4j.editorconfig' version '0.1.0'
    id 'checkstyle'
}

group = 'com.sprint'
version = '0.0.1-SNAPSHOT'
description = 'deokhugam'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    compileOnly 'org.projectlombok:lombok'
    runtimeOnly 'org.postgresql:postgresql'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testCompileOnly 'org.projectlombok:lombok'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testAnnotationProcessor 'org.projectlombok:lombok'

    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    testAndDevelopmentOnly 'org.springframework.boot:spring-boot-docker-compose'
}

jar {
    enabled = false
}

editorconfig {
    includes = ['src/**']
    excludes = ['src/main/resources/**']
}

checkstyle {
    maxWarnings = 0 // 규칙이 어긋나는 코드가 하나라도 있을 경우 빌드 fail을 내고 싶다면 이 선언을 추가한다.
    configFile = file("${rootDir}/rule-config/checkstyle-rules.xml")
    configProperties = ["suppressionFile": "${rootDir}/rule-config/checkstyle-suppressions.xml"]
    toolVersion = "12.3.0"
}

tasks.named('test') {
    useJUnitPlatform()
}

// Gradle이 실행될 때(IntelliJ 동기화 포함) git 훅 경로를 자동 설정
if (file('.git').exists()) {
    providers.exec { commandLine 'git', 'config', 'core.hooksPath', '.githooks' }.result.get()
}


check.dependsOn editorconfigCheck // .editorconfig 적용 (checkstyle이 설정 되어 있을 시, editorconfigCheck 후 checkstyle 진행)
