input {
  file {
    path => "/var/log/app/app*.log"
    start_position => "beginning"
    sincedb_path => "/usr/share/logstash/data/sincedb-app"
    codec => multiline {
      pattern => "^\d{4}-\d{2}-\d{2}"
      negate => "true"
      what => "previous"
      auto_flush_interval => 5
    }
  }
}

filter {
  grok {
    match => {
      "message" => "(?m)%{TIMESTAMP_ISO8601:log_time}\s+\[%{DATA:thread}\]\s+%{LOGLEVEL:log_level}\s+%{NOTSPACE:logger}\s+\[%{DATA:client_ip}\]\s+\[%{DATA:user_id}\]\s+-\s+%{GREEDYDATA:log_message}"
    }
  }

  date {
    match => [ "log_time", "yyyy-MM-dd HH:mm:ss.SSS" ]
    timezone => "Asia/Seoul"
    target => "@timestamp"
  }

  mutate {
    gsub => [ "log_message", "\r", "" ]
  }

  mutate {
    remove_field => [ "event", "host", "@version", "log" ]
  }
  if "_grokparsefailure" not in [tags] {
      mutate { remove_field => [ "message" ] }
    }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "spring-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}